### ISSUE TITLE
Fails to start properly in cosmic desktop enviroment

### ISSUE THREAD

**Issue by RynoGames** [NoRiskClient/noriskclient-launcher#69]
Hello I am a complete noob to github, so excuse me, if I miss something to mention etc. 

I use the latest version of manjaro Linux with comisc dekstop in `1.0.0.alpha.1-1` and use the `nouveau` nvidia driver. `norisk` launches but shows just a black window.
```
no-risk-client
[11-10-2024 13:06:09] INFO - ###############################
[11-10-2024 13:06:09] INFO -
[11-10-2024 13:06:09] INFO -
[11-10-2024 13:06:09] INFO -       NEW LAUNCHER LOG
[11-10-2024 13:06:09] INFO -
[11-10-2024 13:06:09] INFO -
[11-10-2024 13:06:09] INFO - ###############################
[11-10-2024 13:06:09] INFO - Creating launcher directories...
[11-10-2024 13:06:09] INFO - Finish launcher directories...
[11-10-2024 13:06:10] WARN - Tried to initialize the wayland data control protocol clipboard, but failed. Falling back to the X11 clipboard protocol. The error was: Unknown error while interacting with the clipboard: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor

** (no-risk-client:67013): WARNING **: 13:06:10.179: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
[11-10-2024 13:06:10] INFO - URL: https://api.norisk.gg/api/v1/core/online
[11-10-2024 13:06:10] INFO - IsClientRunning is false
thread 'tokio-runtime-worker' panicked at src/minecraft/minecraft_auth.rs:522:77:
called `Result::unwrap()` on an `Err` value: NoCredentialsError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/minecraft/minecraft_auth.rs:522:77:
called `Result::unwrap()` on an `Err` value: NoCredentialsError
[11-10-2024 13:06:10] DEBUG - starting new connection: https://api.norisk.gg/
[11-10-2024 13:06:11] INFO - URL: https://api.norisk.gg/api/v1/launcher/online
[11-10-2024 13:06:11] INFO - Core API online state: true, Launcher API online state: true
[11-10-2024 13:06:11] INFO - API is online!
thread 'tokio-runtime-worker' panicked at src/app/gui.rs:1298:89:
called `Result::unwrap()` on an `Err` value: Datei oder Verzeichnis nicht gefunden (os error 2)
```
Is there anything knwon that doesn't work with `wayland`?

**Comment by TimLohrer** [comment]
Please dont create any issues here, use<https://github.com/NoRiskClient/issues/issues> instead.

& This is known and not our issue. It is in a beta state and you should only use it if you are in the beta. To fix this, delete the accounts.json in the launchers config directory. I use wayland and it works perfectly fine.
